apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  postgres-password: "QEFkbWluMTIz"  # base64 for "@Admin123"
  postgres-username: "cG9zdGdyZXNhZG1pbg==" # base64 for "postgresadmin"
  postgres-db: "dGFza21hbmFnZXI="  # base64 for "taskmanager"
  postgres-host: "cHNxbC10YXNrbWFuYWdlci1kZXYucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t"  # base64 for "psql-taskmanager-dev.postgres.database.azure.com"
  postgres-url: "cG9zdGdyZXM6Ly9wb3N0Z3Jlc2FkbWluOkBBZG1pbjEyM0Bwc3FsLXRhc2ttYW5hZ2VyLWRldi5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi90YXNrbWFuYWdlcj9zc2xtb2RlPXJlcXVpcmU=" 