apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: acrtaskmanagerdev.azurecr.io/task-service:latest
        ports:
        - containerPort: 8082
        env:
        # Database configuration from ConfigMap
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_USER
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_PORT
        - name: POSTGRES_SSL_MODE
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_SSL_MODE
        # Password from Secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password
        # Service configuration
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-url